// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls=WPAppStudio.Controls;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;
using IServices=WPAppStudio.Services.Interfaces;
using IViewModels=WPAppStudio.ViewModel.Interfaces;
using Localization=WPAppStudio.Localization;
using Repositories=WPAppStudio.Repositories;
using Services=WPAppStudio.Services;
using ViewModelsBase=WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Actor_Actoractor ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class Actor_ActoractorViewModel : ViewModelsBase.VMBase, IViewModels.IActor_ActoractorViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.IActor_charactersCollection _actor_charactersCollection;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Actor_ActoractorViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="actor_charactersCollection">The Actor_characters Collection.</param>
        public Actor_ActoractorViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.IActor_charactersCollection actor_charactersCollection)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_actor_charactersCollection = actor_charactersCollection;
        }
		
	
		private ObservableCollection<Entities.charactersSchema> _actor_ActoractorListControlCollection;

        /// <summary>
        /// Actor_ActoractorListControlCollection property.
        /// </summary>		
        public ObservableCollection<Entities.charactersSchema> Actor_ActoractorListControlCollection
        {
            get
            {
				
                if(_actor_ActoractorListControlCollection == null)
					_actor_ActoractorListControlCollection = _actor_charactersCollection.GetData();
				return _actor_ActoractorListControlCollection;     
            }
            set
            {
                SetProperty(ref _actor_ActoractorListControlCollection, value);
            }
        }
	
		private int _actor_ActoractorListControlCollectionPageNumber;

        /// <summary>
        /// Actor_ActoractorListControlCollectionPageNumber property.
        /// </summary>		
        public int Actor_ActoractorListControlCollectionPageNumber
        {
            get
            {
				return _actor_ActoractorListControlCollectionPageNumber;
            }
            set
            {
                SetProperty(ref _actor_ActoractorListControlCollectionPageNumber, value);
            }
        }
	
		private Entities.charactersSchema _selectedActor_ActoractorListControlCollection;

        /// <summary>
        /// SelectedActor_ActoractorListControlCollection property.
        /// </summary>		
        public Entities.charactersSchema SelectedActor_ActoractorListControlCollection
        {
            get
            {
				return _selectedActor_ActoractorListControlCollection;
            }
            set
            {
                _selectedActor_ActoractorListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.IActor_DetailViewModel>(_selectedActor_ActoractorListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the GetActor_ActoractorListControlCollectionCommand command.
        /// </summary>
        public  void GetActor_ActoractorListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				GetActor_ActoractorListControlCollectionData(pageNumber);
        }
		

        private ICommand _getActor_ActoractorListControlCollectionCommand;

        /// <summary>
        /// Gets the GetActor_ActoractorListControlCollectionCommand command.
        /// </summary>
        public ICommand GetActor_ActoractorListControlCollectionCommand
        {
            get { return _getActor_ActoractorListControlCollectionCommand = _getActor_ActoractorListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(GetActor_ActoractorListControlCollectionCommandDelegate); }
        }

        private void GetActor_ActoractorListControlCollectionData(int pageNumber = 0)
        {
				Actor_ActoractorListControlCollectionPageNumber = pageNumber;

                if (pageNumber == 0)
				{
					var items = _actor_charactersCollection.GetData(pageNumber);
                    Actor_ActoractorListControlCollection = items;
				}
                else   
				{
					var items = _actor_charactersCollection.GetData(pageNumber);
                    foreach (var item in items)                    
                        Actor_ActoractorListControlCollection.Add(item);
				}
		}
    }
}
