// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities=WPAppStudio.Entities;
using EntitiesBase=WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// Actor_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface IActor_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentcharactersSchema property.
        /// </summary>
		Entities.charactersSchema CurrentcharactersSchema { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaActor_Detail0 property.
        /// </summary>
		bool HasNextpanoramaActor_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaActor_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaActor_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechActor_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechActor_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareActor_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareActor_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartActor_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartActor_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the NextpanoramaActor_Detail0 command.
        /// </summary>
		ICommand NextpanoramaActor_Detail0 { get; }

        
        /// <summary>
        /// Gets the PreviouspanoramaActor_Detail0 command.
        /// </summary>
		ICommand PreviouspanoramaActor_Detail0 { get; }

	}
}
