// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Actor_charactersCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class Actor_charactersCollection : IActor_charactersCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.charactersSchema> _data = new ObservableCollection<Entities.charactersSchema>
		{
          new Entities.charactersSchema
            {
                Id= new Guid("f4694bcc-2d0d-4828-ae13-62920c05dde3"),
                Title=@" Dakota Fanning",
                Subtitle=@"Jane",
                Image=@"\Images\Item-ca665dfc-a796-4036-b603-616e92d325e7.png",
                Description=@"Jane is a high-ranking member of the Volturi guard in the Twilight Saga. She is the twin sister of Alec, and together they are the Volturi's most powerful offensive weapons. Jane has the ability to induce a crippling, although illusory, pain in other people's minds, which serves greatly in instilling fear and maintaining order to confrontations.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("c78c05e1-256a-4fff-87d4-9dc5395f5390"),
                Title=@"Ashley Greene",
                Subtitle=@"alice cullen",
                Image=@"\Images\Item-848ffb1f-493f-4ecd-be78-9b7fe57ca122.png",
                Description=@"Alice Cullen (born Mary Alice Brandon) is the adopted daughter of Carlisle and Esme Cullen, adoptive sister of Edward and Emmett Cullen, as well as Rosalie Hale and the partner of Jasper Hale.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("cd977189-94da-4e89-8440-9dd4ac2bc866"),
                Title=@"Elizabeth Reaser",
                Subtitle=@"esme cullen",
                Image=@"\Images\Item-fc5a44d9-e2e0-4ce6-b359-2427113b5485.png",
                Description=@"Esme Cullen (born Esme Anne Platt, previously Evenson, born 1895) is the matriarch of the Olympic coven. She is the wife of Carlisle Cullen and the adoptive mother of Alice, Emmett, Edward Cullen, Rosalie and Jasper Hale. Esme is also the adoptive mother-in-law of Bella Swan, and the adoptive grandmother of Renesmee Cullen. She was previously married to Charles Evenson as a human.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("c243a4c4-7174-4d05-a3ee-cff0d4304097"),
                Title=@"Kristen Stewart",
                Subtitle=@"bella swan",
                Image=@"\Images\Item-febed250-205d-4b70-947c-e4e07ee0c019.png",
                Description=@"Isabella Marie ""Bella"" Swan (later Bella Cullen) is a character and the protagonist of the Twilight series, written by Stephenie Meyer. The Twilight series, consisting of the novels Twilight, New Moon, Eclipse, and Breaking Dawn, is primarily narrated from Bella's point of view.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("4a45e74a-6ce0-416e-b580-1cbe9b186419"),
                Title=@"Mackenzie Foy",
                Subtitle=@"Renesmee Cullen",
                Image=@"\Images\Item-8326c7c5-5722-49ed-bc68-56a6b1d429f7.jpg",
                Description=@"Born on September 11, 2006[1] Renesmee (pronounced Ruh-nez-may) ""Nessie"" Carlie Cullen is the resident vampire/human hybrid of the Olympic coven. She is the daughter of Edward Cullen and Bella Swan and the imprintee of Jacob Black. Renesmee's biological paternal grandparents are Edward Sr. and Elizabeth Masen, while on the maternal side, they are Charlie Swan and Renée Dwyer. She is also the adoptive granddaughter of Carlisle and Esme Cullen and the adoptive niece of Jasper and Rosalie Hale, and Alice and Emmett Cullen.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("cbe5b9c8-1a76-4481-b62c-73567729aab2"),
                Title=@"Michael Sheen",
                Subtitle=@"Aro",
                Image=@"\Images\Item-9f518f4a-3cac-44ad-b02c-fa2e897c420f.png",
                Description=@"Aro is one of the three leaders of the Volturi - the dominant coven of the vampire world. He is widely accepted as the overall leader of the Volturi, and shows the gift of tactile telepathy, being capable of reading someone's thoughts and memories with a single touch. He is the husband of Sulpicia and the older brother of Didyme. He uses Chelsea to change the loyalties of the vampires whom he wants to join the Volturi and secure his power status.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("19ed55e2-edbb-4764-a4f5-7315921fd19c"),
                Title=@"Peter Facinelli",
                Subtitle=@"Carlisle Cullen",
                Image=@"\Images\Item-cc320667-f0cc-473c-bf1e-f9a68f977bd9.jpg",
                Description=@"Carlisle Cullen (pronounced Car-lyle), also known as ""stregone benefico"", was born in 1640 in London, England, is the founder and leader of the Olympic coven. He is the second husband of Esme Cullen and the adoptive father of Emmett, Alice, Edward Cullen, and Jasper and Rosalie Hale. He is also the adoptive father-in-law of Bella Swan and adoptive grandfather of Renesmee Cullen.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("4c451828-5771-4797-8627-a810a1eb09c8"),
                Title=@"Robert Pattinson",
                Subtitle=@"edward cullen",
                Image=@"\Images\Item-aadf3fac-511a-4d5c-86e6-334faaba6a11.png",
                Description=@"Edward Cullen (né Edward Anthony Masen) is a fictional character in Stephenie Meyer's Twilight series. He is featured in the books Twilight, New Moon, Eclipse and Breaking Dawn, and their corresponding film adaptations, and the as yet unfinished novel Midnight Sun - a re-telling of the events of Twilight from Edward's perspective. Edward is a telepathic Vampire who, over the course of the series, falls in love with, marries, and has a child with Bella Swan, a human teenager who later chooses to become a vampire as well.",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("d9908094-5be0-4d98-8e94-aa9225223314"),
                Title=@"Taylor Lautner",
                Subtitle=@"jacob black",
                Image=@"\Images\Item-ab9ed704-9555-4f8e-8a12-5b9e8f08199a.png",
                Description=@"acob ""Jake"" Black is a character in the Twilight series by Stephenie Meyer. He is described as a Native American of the Quileute tribe in La Push, near Forks, Washington. In the second book of the series, he discovers that he can shapeshift into a wolf. For the majority of the series, Jacob competes with Edward Cullen for Bella Swan's love. ",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of charactersSchema items.
        /// </summary>
        /// <returns>An observable collection of charactersSchema items.</returns>
        public ObservableCollection<Entities.charactersSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.charactersSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of charactersSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of charactersSchema items.</returns>
        public ObservableCollection<Entities.charactersSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.charactersSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.charactersSchema Previous(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.charactersSchema Next(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

