// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// TheStoryDataSource_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class TheStory_TheStoryDataSource : ITheStory_TheStoryDataSource 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<br><b><b><i>Twilight is a 2008 American romantic fantasy film based on Stephenie Meyer's popular novel of the same name. Directed by Catherine Hardwicke, the film stars Kristen Stewart and Robert Pattinson. It is the first film in The Twilight Saga film series.</i></b><br /><span class=""wysiwyg-font-size-medium""><br /></span><br /></b></br>";
        }
	}
}

